mqtt:
  host: 127.0.0.1
  port: 1883
  user: user
  password: pass
  client_id: atlas_copco_parser
  tls: false
discovery_prefix: homeassistant
question_templates:
- http://{ip}/q?m={question}
- http://{ip}/mem/{question}
- http://{ip}/api/mb?m={question}
devices:
- name: eftool-bw-b2-f3-air11
  ip: 10.60.23.11
  device_type: GA15VP13
- name: eftool-bw-b2-f3-air12
  ip: 10.60.23.12
  device_type: GA15VS23A
