name: MK5S Client
version: "0.1.3"
slug: mk5s_client
description: Polls MK5S controller and exposes confirmed-good metrics to Home Assistant
url: https://github.com/ErnstFinkAG/ha_addons
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: services
init: false
boot: auto
image: null
options:
  host: "10.60.23.11"
  interval: 10
  timeout: 5
  verbose: true
schema:
  host: str
  interval: int
  timeout: int
  verbose: bool
