name: MK5S Client
version: 0.1.2
slug: mk5s_client
description: Polls a MK5S controller and logs confirmed-good metrics from an MK5S controller.
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: services
init: false
boot: auto
options:
  host: 10.60.23.11
  interval: 10
  timeout: 5
  verbose: true
schema:
  host: str
  interval: int
  timeout: int
  verbose: bool
