name: MK5S Client
slug: mk5s_client
version: "0.1.3"
description: "Poll MK5S via mkv.cgi; log QUESTION/ANSWER; decode confirmed-good values; expose to Home Assistant."
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: services
init: false
boot: auto
host_network: true
ingress: false
panel_icon: mdi:compressor
options:
  host: "10.60.23.11"
  interval: 10
  timeout: 5
  verbose: true
schema:
  host: str
  interval: int
  timeout: int
  verbose: bool
